### ISSUE TITLE
Sometimes pickle file is broken if I stop make-index command by C-c

### ISSUE THREAD

**Issue by shibayu36** [shibayu36/chat-hatenablog#16]
```
$ ./chat-hatenablog make-index --mt-file blog.shibayu36.org.export.txt
Traceback (most recent call last):
  File "/Users/yuki.shibazaki/development/src/github.com/shibayu36/chat-hatenablog/./chat-hatenablog", line 51, in <module>
    main()
  File "/Users/yuki.shibazaki/development/src/github.com/shibayu36/chat-hatenablog/./chat-hatenablog", line 47, in main
    args.func(args)
  File "/Users/yuki.shibazaki/development/src/github.com/shibayu36/chat-hatenablog/chat_hatenablog/make_index_command.py", line 91, in make_index
    vs = VectorStore(index_file)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuki.shibazaki/development/src/github.com/shibayu36/chat-hatenablog/chat_hatenablog/vector_store.py", line 40, in __init__
    self.cache = pickle.load(open(self.index_file, "rb"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
```

**Comment by shibayu36** [comment]
tempfile pattern?

```python
import os
import tempfile

# Write the pickled data to a temporary file
with tempfile.NamedTemporaryFile(mode="wb", delete=False) as tmp_file:
    pickle.dump(self.cache, tmp_file)
    temp_file_path = tmp_file.name

# Replace the original index file with the temporary file
os.replace(temp_file_path, self.index_file)
```

**Comment by shibayu36** [comment]
https://stackoverflow.com/questions/7645338/how-to-do-atomic-file-replacement
